/**
 * Jobs API (nodeJS)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import {
  LoginUserRequest,
  loginUserRequestSchema,
} from '../models/loginUserRequest';
import {
  RegisterUserRequest,
  registerUserRequestSchema,
} from '../models/registerUserRequest';
import { BaseController } from './baseController';

export class AuthController extends BaseController {
  /**
   * @param body
   * @return Response from the API call
   */
  async registerUser(
    body: RegisterUserRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('POST', '/auth/register');
    const mapped = req.prepareArgs({ body: [body, registerUserRequestSchema] });
    req.json(mapped.body);
    req.authenticate(false);
    return req.call(requestOptions);
  }

  /**
   * @param body
   * @return Response from the API call
   */
  async loginUser(
    body: LoginUserRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('POST', '/auth/login');
    const mapped = req.prepareArgs({ body: [body, loginUserRequestSchema] });
    req.json(mapped.body);
    req.authenticate(false);
    return req.call(requestOptions);
  }
}
