/**
 * Jobs API (nodeJS)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import {
  DeleteJobRequest,
  deleteJobRequestSchema,
} from '../models/deleteJobRequest';
import { NewJobRequest, newJobRequestSchema } from '../models/newJobRequest';
import {
  UpdateJobRequest,
  updateJobRequestSchema,
} from '../models/updateJobRequest';
import { BaseController } from './baseController';

export class JobsController extends BaseController {
  /**
   * @param body
   * @return Response from the API call
   */
  async newJob(
    body: NewJobRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('POST', '/jobs');
    const mapped = req.prepareArgs({ body: [body, newJobRequestSchema] });
    req.json(mapped.body);
    return req.call(requestOptions);
  }

  /**
   * @return Response from the API call
   */
  async getAllJobs(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('GET', '/jobs');
    return req.call(requestOptions);
  }

  /**
   * @return Response from the API call
   */
  async getOneJob(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('GET', '/jobs/62881b4b4d5d7e5eba4d7c7b');
    return req.call(requestOptions);
  }

  /**
   * @param body
   * @return Response from the API call
   */
  async updateJob(
    body: UpdateJobRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('PATCH', '/jobs/62881b4b4d5d7e5eba4d7c7b');
    const mapped = req.prepareArgs({ body: [body, updateJobRequestSchema] });
    req.json(mapped.body);
    return req.call(requestOptions);
  }

  /**
   * @param body
   * @return Response from the API call
   */
  async jobs(
    body: DeleteJobRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('DELETE', '/jobs/62881b4b4d5d7e5eba4d7c7b');
    const mapped = req.prepareArgs({ body: [body, deleteJobRequestSchema] });
    req.json(mapped.body);
    return req.call(requestOptions);
  }
}
