/**
 * Jobs API (nodeJS)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface DeleteJobRequest {
  company: string;
}

export const deleteJobRequestSchema: Schema<DeleteJobRequest> = object({
  company: ['company', string()],
});
