/**
 * Jobs API (nodeJS)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface NewJobRequest {
  company: string;
  position: string;
}

export const newJobRequestSchema: Schema<NewJobRequest> = object({
  company: ['company', string()],
  position: ['position', string()],
});
