/**
 * Jobs API (nodeJS)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface RegisterUserRequest {
  name: string;
  password: string;
  email: string;
}

export const registerUserRequestSchema: Schema<RegisterUserRequest> = object({
  name: ['name', string()],
  password: ['password', string()],
  email: ['email', string()],
});
